### ISSUE TITLE
Spacing on Tagline

### ISSUE THREAD

**Issue by LloydLNewman** [ResearchHub/discussion#13]
Is it possible to add line breaks to the tagline section? If I try to do it now it shows up on the home page but not in the post itself.

**Comment by dhimmel** [comment]
Do you have a preference on whether it _should_ be possible to add newlines in a tagline?

IMO it's probably best to avoid newlines. I view the tagline a lot like an HTML meta tag, which only supports plain text and not [line breaks](https://stackoverflow.com/questions/6179889). Thinking that taglines should be as compact as possible to fit next to post titles in result views.

**Comment by LloydLNewman** [comment]
Fair, more so the lack of standardization was off putting. Closing.
