### ISSUE TITLE
Search on mobile

### ISSUE THREAD

**Issue by ZacharyMiller06** [ResearchHub/discussion#2]
Is this currently possible?

**Comment by dhimmel** [comment]
I don't see a way when I change my browser to "Pixel 2" screen dimensions:

> ![image](https://user-images.githubusercontent.com/1117703/71626212-02da6500-2bba-11ea-906c-2bf8f61339f7.png)

**Comment by dhimmel** [comment]
Note the search bar gets hidden even on desktop browsers when the width is reduced. I could imagine some split screen configurations would actually make the search bar disappear.

**Comment by lightninglu10** [comment]
Currently no way to search on mobile, we need to add the search bar for small screens.
