### ISSUE TITLE
"F1000 Research"-Published Paper Submission Automatically "Removed by moderator" even though it meets guidelines

### ISSUE THREAD

**Issue by monadnoc** [ResearchHub/discussion#21]
A paper that meets guidelines is being "removed by moderator" immediately upon submission. The paper meets license guidelines and peer review guidelines. For reference: the paper is 
https://dx.doi.org/10.12688%2Fwellcomeopenres.15191.1

This has happened to me before for papers published via the peer review mechanism of F1000 Research platform

**Comment by lightninglu10** [comment]
Can you link your profile? You might've gotten shadow banned by mistake.

**Comment by monadnoc** [comment]
https://www.researchhub.com/user/432393/contributions

**Comment by lightninglu10** [comment]
I just looked into it -- looks like the issue is that the DOI wasn't recorded on it. Did you have a DOI when you submitted?

**Comment by lightninglu10** [comment]
I just brought this paper back BTW: https://www.researchhub.com/paper/851274/raincloud-plots-a-multi-platform-tool-for-robust-data-visualization

**Comment by monadnoc** [comment]
Mobile webui did not ask for DOI when uploading fyi but thanks a lot for quick response and closure (first time submitting on mobile)
