### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Philip-AG** [ResearchHub/discussion#23]
Issue 1: When recieving notifications on RH, I find there to be a discrepancy between the "notification itself" and "what you are actually notified about". This not only happens for personal notifications but also for notifications on the live feed.

For instance, a paper I uploaded got an 10 RSC contribution to support it.
Yet, the notification tells me I was awarded 10 RSC for my comment on this paper.

![image](https://user-images.githubusercontent.com/81303478/112307815-b1783300-8ca1-11eb-86c1-c507a4869b08.png)

Issue 2: I can only see my personal notifications once. If I have clicked them in the past, they will disappear and I can't see what I got notified about before anymore.

![image](https://user-images.githubusercontent.com/81303478/112308244-39f6d380-8ca2-11eb-9913-92815d30e679.png)

**Comment by lightninglu10** [comment]
This is something we're looking into!
