### ISSUE TITLE
Unable to upvote posts from Author's profile page

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#3]
When viewing an author's profile page, I am unable to upvote any of their posts. 

In the image below, when I clicked the upvote/downvote button - it was not registered. 

![Screen Shot 2020-01-02 at 10 48 47 AM](https://user-images.githubusercontent.com/49012969/71676305-e2dbaa80-2d4d-11ea-9617-4904ecb338e5.png)

I'm not sure if this is a feature or a bug. I think it might be useful to keep the friction that makes it more difficult for people to blindly upvote the authors they like. Hopefully, this will force upvotes to come from more organic browsing of RH.

**Comment by dhimmel** [comment]
Looks like reddit allows upvoting posts but not individual comments from a user page ([example](https://www.reddit.com/user/Yayeahh/)):

> ![image](https://user-images.githubusercontent.com/1117703/71677032-b1fc7500-2d4f-11ea-9e8e-f6884883ebf2.png)

The RH contributions page ([example](https://www.researchhub.com/user/62/contributions)) currently includes both paper uploads and comments. In addition to the voting button not working, I don't see a way to go from comment on contributions page to the comment as part of the parent discussion.

Perhaps the reason reddit doesn't allow comment upvotes from the user page is that comment value depend on context that is not visible from that view. Whereas a post is more self-contained.

I don't have a strong preference at the moment whether we should allow voting from the user page. In the longterm, I'd like incentives to create honest and diligent voting, such that we could allow up-voting from a contributions page without a risk of spam or favoritism. But that seems like a long way down the road.

**Comment by joycesticks** [comment]
> In the longterm, I'd like incentives to create honest and diligent voting, such that we could allow up-voting from a contributions page without a risk of spam or favoritism. 

Agreed, getting the incentives right is the more important challenge here long-term. 

@lightninglu10 what do you think about allowing upvote/downvoting on the user's profile page?
