### ISSUE TITLE
">" on profile page malfunctioning 

### ISSUE THREAD

**Issue by Philip-AG** [ResearchHub/discussion#41]
When browsing on an android mobile phone and you have a look at a user's profile it is impossible to use the ">" button to look through different profile sections. The button is non-reactive.

![20210424_225934](https://user-images.githubusercontent.com/81303478/115972828-0df49980-a551-11eb-992e-2e3d530279a7.jpg)

**Comment by thomas-vu** [comment]
Fixed!
