### ISSUE TITLE
Problem with "Supported pages" section on profile page 

### ISSUE THREAD

**Issue by Philip-AG** [ResearchHub/discussion#43]
On my profile page the amount of supported papers is displayed as 0.
However, I have supported 7 papers in total.

![image](https://user-images.githubusercontent.com/81303478/116433914-3bd82780-a84a-11eb-95e1-2ed1a0835b2b.png)

**Comment by lightninglu10** [comment]
@le-sun is investigating

**Comment by lightninglu10** [comment]
@le-sun is this resolved? if so, let's close out the issue

**Comment by le-sun** [comment]
> @le-sun is this resolved? if so, let's close out the issue

@lightninglu10 Sorry, it's still unresolved. I thought you were going to take it over since it was a frontend authentication issue
