### ISSUE TITLE
Paper page layout on small screen (android)

### ISSUE THREAD

**Issue by Philip-AG** [ResearchHub/discussion#44]
The paper page layout seems to be too small when looking on an android phone.
The menu logo (three horizontal stripes) is not located in the upper right corner for instance.
![Screenshot_20210430-212605_Chrome](https://user-images.githubusercontent.com/81303478/116755174-535e0e80-aa0a-11eb-942b-d72e094ef9a7.jpg)

**Comment by lightninglu10** [comment]
Deployed fix, should be out in 15 minutes.
