### ISSUE TITLE
3rd level replies are difficult to discover within the paper page

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#45]
Once a reply goes to the 3rd level, it is automatically hidden until the [replies (x)] button is pressed. Unfortunately, this button is VERY subtle and does not draw enough attention to the fact there is a discussion available to view. See image below from this post https://www.researchhub.com/paper/951520/pigeons-columba-livia-as-trainable-observers-of-pathology-and-radiology-breast-cancer-images#discussion 

![Screen Shot 2021-05-03 at 1 13 26 PM](https://user-images.githubusercontent.com/49012969/116909108-b968b280-ac11-11eb-840f-03ca131252bd.png)

We should either 1.) automatically show 3rd/4th/5th level comments or 2.) make this button much more prominent when there is a hidden reply that can be viewed

**Comment by lightninglu10** [comment]
Fixed
