### ISSUE TITLE
Must scroll down to the end of the paper page to submit a longer in-line comment

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#49]
I just tried to make an inline comment on this paper (https://www.researchhub.com/paper/1043530/effects-of-twelve-sessions-of-high-temperature-sauna-baths-on-body-composition-in-healthy-young-men) where I wrote a paragraph and included a youtube video. 

Unfortunately, due to the comment's length, I needed to scroll down the screen in order to hit the submit button. Instead of just being required to scroll down the length of the comment, I had to scroll to the bottom of the paper before the 'submit' button appeared. 

Comment with submit button unreachable: 

<img width="1277" alt="Screen Shot 2021-05-19 at 11 58 24 AM" src="https://user-images.githubusercontent.com/49012969/118845552-dfd94f80-b899-11eb-9858-6ffb24aef052.png">

Comment once I scrolled down to the bottom of the paper page: 

<img width="1313" alt="Screen Shot 2021-05-19 at 12 01 29 PM" src="https://user-images.githubusercontent.com/49012969/118845641-f54e7980-b899-11eb-85fa-36da2449d08c.png">

We should fix the scroll so users just need to scroll down the length of their comment.

**Comment by lightninglu10** [comment]
Fixed!
