### ISSUE TITLE
Searching for papers & Adding authors

### ISSUE THREAD

**Issue by inezpereira** [ResearchHub/discussion#57]
I am trying to add a preprint to Research Hub, but I get the message that "a paper with this URL already exists".
How can I search for it and also add myself as an author? I do not see any search bar.
I am on macOS Big Sur 11.3.1 and have tried opening researchhub.com on Brave, Safari and Google Chrome.

Thanks!

A screenshot on my desktop:
<img width="1438" alt="Screenshot 2021-05-26 at 17 55 40" src="https://user-images.githubusercontent.com/20027814/119700815-f9f3ce80-be53-11eb-80cf-a0f584fa2c87.png">

The message I get:
![image](https://user-images.githubusercontent.com/20027814/119699662-af258700-be52-11eb-9e7f-f6a35156954e.png)

**Comment by thomas-vu** [comment]
We are currently reworking our search system and the search bar has been temporarily disabled. Sorry for the inconvenience!

I found the URL for your paper: https://www.researchhub.com/paper/939035/82toLjuzqVcytVpORi1cdmlwI6A6Bydg
