### ISSUE TITLE
Issue with Slack invite link on RH homepage

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#59]
Someone just reached out to hello@researchhub.com to let us know they were having trouble with the Slack link of the homepage. Does the button point to https://join.slack.com/t/researchhub-community/shared_invite/zt-oytw02om-w1cQc2Kcjs7vg3tZHqt9Ww ?

<img width="504" alt="Screen Shot 2021-05-26 at 1 37 21 PM" src="https://user-images.githubusercontent.com/49012969/119706069-81771880-be27-11eb-85d3-6e9a09a7489a.png">

**Comment by thomas-vu** [comment]
Right now it points to https://join.slack.com/t/researchhub-community/shared_invite/zt-iqred46f-f0j0M6_ZxtliD~UszPyWEQ

**Comment by joycesticks** [comment]
Thanks for the quick info, Thomas! Can we switch it to the link I posted in the initial issue? We just upgraded to the paid Slack which gives us an evergreen invite (instead of one that expires every 30 days).

**Comment by thomas-vu** [comment]
I'll get on it!
