### ISSUE TITLE
Server Error 500 when trying to upload a paper

### ISSUE THREAD

**Issue by dhimmel** [ResearchHub/discussion#6]
Trying to upload https://eprint.iacr.org/2020/014.pdf which gives [this rh url](https://www.researchhub.com/paper/upload/info?uploadPaperTitle=SHA-1%20is%20a%20Shambles%20-%20First%20Chosen-Prefix%20Collision%20on%20SHA-1%20and%20Application%20to%20the%20PGP%20Web%20of%20Trust)

Tag line:

> This study demonstrates a weakness in the SHA-1 hashing algorithm where two inputs are combined with two prefixes to cause a hash collision.

The "Something went wrong" dialogue briefly appears and then disappears before I can screenshot it.

**Comment by lightninglu10** [comment]
Yep, saw an issue -- on it
