### ISSUE TITLE
New post from Nicolas didn't show up in the live feed

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#78]
Nicolas just posted this but it does not appear in the livefeed: [https://www.researchhub.com/post/4/research-poster:-an-analysis-of-florida-water-quality,-2001---2017](https://www.researchhub.com/post/4/research-poster:-an-analysis-of-florida-water-quality,-2001---2017)

<img width="1056" alt="Screen Shot 2021-06-25 at 1 15 27 PM" src="https://user-images.githubusercontent.com/49012969/123461705-6a0e8500-d5b7-11eb-9217-9144a0ddbe7d.png">

**Comment by lightninglu10** [comment]
This issue is now fixed
