### ISSUE TITLE
Unable to add OA PDF to a paper post - but the text was still rendered 

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#82]
I just tried to add the PDF from this paper to a recent RH post [https://www.researchhub.com/paper/1265899/animal-protein-versus-plant-protein-in-supporting-lean-mass-and-muscle-strength-a-systematic-review-and-meta-analysis-of-randomized-controlled-trials](https://www.researchhub.com/paper/1265899/animal-protein-versus-plant-protein-in-supporting-lean-mass-and-muscle-strength-a-systematic-review-and-meta-analysis-of-randomized-controlled-trials)

After adding the PDF, I saw a message that said "PDF added successfully" - but the page did not display the PDF

<img width="857" alt="Screen Shot 2021-07-07 at 10 57 50 AM" src="https://user-images.githubusercontent.com/49012969/124782607-5ac1fc80-df12-11eb-957b-c47fe3da169d.png">

After refreshing the page, there was no PDF attached to the post - but the OA text was rendered within the post itself.

<img width="864" alt="Screen Shot 2021-07-07 at 10 59 52 AM" src="https://user-images.githubusercontent.com/49012969/124782747-76c59e00-df12-11eb-8f8a-9a010e72c2e7.png">

**Comment by lightninglu10** [comment]
issue fixed!
