### ISSUE TITLE
Unable to support new 'post' type with RSC 

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#83]
I wanted to support Phillip's new post with some RSC, but there is no button that would allow me to do that. We should add the ability to support the new post type 

<img width="924" alt="Screen Shot 2021-07-07 at 8 02 29 PM" src="https://user-images.githubusercontent.com/49012969/124842814-72bf6d80-df5e-11eb-93eb-fb636777e8aa.png">

**Comment by thomas-vu** [comment]
Working on this!
