### ISSUE TITLE
Papers that have been removed by mods are still appearing in the homepage's live feed

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#84]
The two posts highlighted in red in the below image were removed by moderators, but they are still appearing in the homepage's live feed. 

<img width="1433" alt="Screen Shot 2021-07-08 at 12 39 18 PM" src="https://user-images.githubusercontent.com/49012969/124960082-f07c8b00-dfe9-11eb-97ad-edecedc98b34.png">

They do not appear in the dedicated live feed page:

<img width="1332" alt="Screen Shot 2021-07-08 at 12 41 36 PM" src="https://user-images.githubusercontent.com/49012969/124960015-d9d63400-dfe9-11eb-8bc0-5044fa954833.png">

**Comment by le-sun** [comment]
Fixed in lastest pr
