### ISSUE TITLE
Reputation / RSC doesn't seem to be updating

### ISSUE THREAD

**Issue by maps-apps-n** [ResearchHub/discussion#86]
Paper getting upvotes doesn't seem to be updating Reputation / RSC

**Comment by lightninglu10** [comment]
Can you paste the paper that's getting upvotes, but you're not receiving RSC?

**Comment by maps-apps-n** [comment]
Thanks, it's: 
https://www.researchhub.com/paper/1265927/quantifying-the-impact-of-the-covid-19-pandemic-restrictions-on-co-co2-and-ch4-in-downtown-toronto-using-open-path-fourier-transform-spectroscopy 

Could be there were some downvotes in others, i'm not keeping track of those.

**Comment by maps-apps-n** [comment]
Seems to be solved. RSC is updating now.
