### ISSUE TITLE
Deleted post still popping up in live feed

### ISSUE THREAD

**Issue by Philip-AG** [ResearchHub/discussion#91]
Following post was deleted (screenshot 1), but a notification about its creation still shows up on the live feed (screenshot 2).

![image](https://user-images.githubusercontent.com/81303478/126607133-ffcfbab4-76c9-45a1-8c7e-a8cf7522a080.png)

![image](https://user-images.githubusercontent.com/81303478/126607080-1c243f93-e74b-4ee8-bbd0-eceb812849b0.png)

**Comment by le-sun** [comment]
Fixed
