### ISSUE TITLE
A deleted post has not been removed from the live feed

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#93]
<img width="1055" alt="Screen Shot 2021-07-28 at 9 37 58 AM" src="https://user-images.githubusercontent.com/49012969/127332089-3d1ab24b-8d9f-415f-8628-141b5e1f7b5c.png">

The [post](https://www.researchhub.com/post/63/question) marked in red was deleted ~12 hours ago, but it still remains in the live feed. Here's a picture of the post's paper page for reference: 

<img width="1293" alt="Screen Shot 2021-07-28 at 9 39 59 AM" src="https://user-images.githubusercontent.com/49012969/127332226-68b6d32a-dcfa-457c-be5e-85297d350aac.png">

**Comment by le-sun** [comment]
Fixed
