### ISSUE TITLE
My newest "post" is displayed 3x in the homepage's live feed

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#94]
I just posted [this question](https://www.researchhub.com/post/64/what-role-does-epigenetics-play-in-the-etiology-of-depression), and the homepage live feed has it displayed numerous times: 

<img width="1309" alt="Screen Shot 2021-07-28 at 4 08 47 PM" src="https://user-images.githubusercontent.com/49012969/127388917-424494e5-b0fe-4373-a886-571ff0480aba.png">

**Comment by thomas-vu** [comment]
Strange, it only appears once for me:
<img width="1241" alt="Screen Shot 2021-07-28 at 2 18 43 PM" src="https://user-images.githubusercontent.com/22990196/127390034-fdf4bb94-47ab-438e-b7cb-870e5497d354.png">

**Comment by lightninglu10** [comment]
It may be because Joyce is part of all 3 hubs and it's not deduping.

**Comment by thomas-vu** [comment]
Just tested, and that does seem to be the issue!

**Comment by le-sun** [comment]
Fixed
