### ISSUE TITLE
A notification showing that my post was supported with RSC has the wrong copy

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#95]
In the notification - should "researchhubpost" just be "post"?

<img width="484" alt="Screen Shot 2021-07-30 at 7 56 24 PM" src="https://user-images.githubusercontent.com/49012969/127721965-1a3954f2-b305-463e-a707-1e17a34dc3b5.png">

**Comment by thomas-vu** [comment]
Yep, I'll fix up notifications next week.

**Comment by lightninglu10** [comment]
I pushed a textual change to this Friday, but I think there's still a bug with the link.
