### ISSUE TITLE
Top-rated filter broken for MyHub's section

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#96]
Reported by Shrey Makwana in the #bug_reports community Slack channel: 

"Hello Everyone, I am not sure if this bug has been reported already but the top-rated filter is not working for any of the categories in the MyHub section, I am not sure if it is supposed to work or it always has been this way. Attaching images for more clarification."

![bug-1](https://user-images.githubusercontent.com/49012969/127779634-727dbcca-9583-441b-ba21-72bc124baf85.PNG)

![bug-2](https://user-images.githubusercontent.com/49012969/127779649-c05b1948-efd7-423d-a785-a2c07c18b871.PNG)

**Comment by lightninglu10** [comment]
I don't think there's a bug here -- I think that there were either no papers published that day at the time the user tried to look at it, or no upvotes.
