### ISSUE TITLE
A deleted post is still able to be supported with RSC

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#97]
This post was deleted over the weekend but is still receiving supported RSC from users: [https://www.researchhub.com/post/66/covid-19](https://www.researchhub.com/post/66/covid-19)

<img width="1019" alt="Screen Shot 2021-08-02 at 11 34 46 AM" src="https://user-images.githubusercontent.com/49012969/127887321-15642533-98e6-4fc3-a3c0-eb8da3be0032.png">

**Comment by lightninglu10** [comment]
@le-sun we need to block on the backend users from being able to support deleted papers.
