### ISSUE TITLE
A paper I just uploaded had its title in the live feed changed to "undefined" 

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#98]
I just submitted [this paper](https://www.researchhub.com/paper/1266047/nasal-oxytocin-for-the-treatment-of-psychiatric-disorders-and-pain-achieving-meaningful-brain-concentrations), and the livefeed shows the title is "undefined"

<img width="1046" alt="Screen Shot 2021-08-04 at 12 21 02 PM" src="https://user-images.githubusercontent.com/49012969/128217668-2623826a-0f73-4c15-b8ec-5b2abca33a19.png">

When I click into the paper's information to edit the title - the editorialized title has been automatically set as "undefined" 

<img width="851" alt="Screen Shot 2021-08-04 at 12 23 03 PM" src="https://user-images.githubusercontent.com/49012969/128217777-382cdddd-5a02-41f5-a4e9-79b8881b6b20.png">

**Comment by calvinhlee23** [comment]
I've updated the title. Trying to reproduce the bug.

**Comment by lightninglu10** [comment]
Fixed
