### ISSUE TITLE
Discrepancy paper score displays

### ISSUE THREAD

**Issue by Philip-AG** [ResearchHub/discussion#99]
There seems to be a discrepancy in paper score between display on the home page and the paper page itself.

Home page (score: 5)
![image](https://user-images.githubusercontent.com/81303478/128827109-49ef2d05-50c5-48b3-8239-b54309afa654.png)

Paper page (score: 30)
![image](https://user-images.githubusercontent.com/81303478/128827181-62a0a3c9-3e5b-4152-9a6b-ae2465b45501.png)

**Comment by lightninglu10** [comment]
Just pushed a fix!
